-- Migration: Update product image_url fields to match product image files
-- Maps each product to its representative image in /product-images/

UPDATE products SET image_url = '/product-images/Semaglutide_5mg.png' WHERE name = 'Semaglutide';
UPDATE products SET image_url = '/product-images/Tirzepatide_5mg.png' WHERE name = 'Tirzepatide';
UPDATE products SET image_url = '/product-images/Retatrutide_5mg.png' WHERE name = 'Retatrutide';
UPDATE products SET image_url = '/product-images/BPC-157-5mg.png' WHERE name = 'BPC 157';
UPDATE products SET image_url = '/product-images/111_TB-500_5mg.png' WHERE name = 'TB500(Thymosin B4 Acetate）';
UPDATE products SET image_url = '/product-images/BPC-157-TB-10mg.png' WHERE name = 'BPC 5mg + TB 5mg';
UPDATE products SET image_url = '/product-images/BPC-157-TB-20mg.png' WHERE name = 'BPC 10mg + TB 10mg';
UPDATE products SET image_url = '/product-images/Glow_70mg.png' WHERE name = '(GLOW) BPC 10mg+GHK-Cu50mg+Tb500 10mg';
UPDATE products SET image_url = '/product-images/41_GHK-Cu_50mg.png' WHERE name = 'GHK-CU';
UPDATE products SET image_url = '/product-images/10_AHK-Cu_100mg.png' WHERE name = 'AHK-CU';
UPDATE products SET image_url = '/product-images/CJC-1295-5mg.png' WHERE name = 'CJC-1295 with DAC';
UPDATE products SET image_url = '/product-images/CJC-1295-NODAC-IPA-10mg.png' WHERE name = 'CJC-1295 NO DAC 5mg + IPA5mg';
UPDATE products SET image_url = '/product-images/CJC-1295-NODAC-10mg.png' WHERE name = 'CJC-1295 NO DAC';
UPDATE products SET image_url = '/product-images/27_Cagrilintide_5mg_blend.png' WHERE name = 'CagriSema';
UPDATE products SET image_url = '/product-images/25_Cagrilintide_5mg.png' WHERE name = 'Cagrilintide';
UPDATE products SET image_url = '/product-images/Cerebrolysin_60mg.png' WHERE name = 'Cerebrolysin 60mg';
UPDATE products SET image_url = '/product-images/DSIP_5mg.png' WHERE name = 'DSIP';
UPDATE products SET image_url = '/product-images/Epithalon-10mg.png' WHERE name = 'Epithalon';
UPDATE products SET image_url = '/product-images/Glutathione-600mg.png' WHERE name = 'Glutathione';
-- HCG: no matching image available, skipped
UPDATE products SET image_url = '/product-images/49_HGH_10iu.png' WHERE name = 'HGH 191AA (Somatropin）';
UPDATE products SET image_url = '/product-images/HyaluronicAcid_5ml.png' WHERE name = 'hyaluronic acid-5mg *1 vials';
UPDATE products SET image_url = '/product-images/48_Hexarelin_5mg.png' WHERE name = 'Hexarelin Acetate';
UPDATE products SET image_url = '/product-images/56_Insulin_3ml.png' WHERE name = 'Insulin-1vial';
UPDATE products SET image_url = '/product-images/54_IGF-1-LR3_1mg.png' WHERE name = 'IGF-1LR3';
UPDATE products SET image_url = '/product-images/57_Ipamorelin_5mg.png' WHERE name = 'Ipamorelin';
UPDATE products SET image_url = '/product-images/59_Kisspeptin-10_5mg.png' WHERE name = 'KissPeptin-10';
UPDATE products SET image_url = '/product-images/03_KPV_5mg.png' WHERE name = '(KPV) LYSINE-PROLINE-VALINE';
UPDATE products SET image_url = '/product-images/Klow_80mg.png' WHERE name = '(KLOW) GHK-CU50+TB10+BC10+KPV10';
UPDATE products SET image_url = '/product-images/70_MOTS-C_10mg.png' WHERE name = 'MOTS-C';
UPDATE products SET image_url = '/product-images/MT-1_10mg.png' WHERE name = 'MT1 5mg Melatonin';
UPDATE products SET image_url = '/product-images/72_MT-2_10mg.png' WHERE name = 'MT-2 (Melanotan 2 Acetate)';
UPDATE products SET image_url = '/product-images/69_Mazdutide_10mg.png' WHERE name = 'Mazdutide';
UPDATE products SET image_url = '/product-images/NAD+_100mg.png' WHERE name = 'NAD';
UPDATE products SET image_url = '/product-images/106_Snap-8_10mg.png' WHERE name = 'Snap-8';
UPDATE products SET image_url = '/product-images/76_Oxytocin_2mg.png' WHERE name = 'Oxytocin Acetate*2mg';
-- PNC-27: no matching image available, skipped
UPDATE products SET image_url = '/product-images/78_Pinealon_5mg.png' WHERE name = 'Pinealon';
UPDATE products SET image_url = '/product-images/81_PT-141_10mg.png' WHERE name = 'PT-141';
UPDATE products SET image_url = '/product-images/ARA-290 10mg.png' WHERE name = 'Ara-290';
UPDATE products SET image_url = '/product-images/102_Sermorelin_5mg.png' WHERE name = 'Sermorelin Acetate';
UPDATE products SET image_url = '/product-images/110_Survodutide_10mg.png' WHERE name = 'Survodutide';
UPDATE products SET image_url = '/product-images/92_Selank_5mg.png' WHERE name = 'Selank';
UPDATE products SET image_url = '/product-images/117_Thymosin-Alpha-1_5mg.png' WHERE name = 'Thymosin Alpha-1';
UPDATE products SET image_url = '/product-images/113_Tesamorelin_5mg.png' WHERE name = 'Tesamorelin';
UPDATE products SET image_url = '/product-images/05_VIP_5mg.png' WHERE name = '(VIP) Vasoactive Intestinal Peptide';
UPDATE products SET image_url = '/product-images/100_Semax_5mg.png' WHERE name = 'Semax';
UPDATE products SET image_url = '/product-images/BotulinumToxin_100iu.png' WHERE name = 'Botulinum toxin';
UPDATE products SET image_url = '/product-images/62_Lemon-Bottle_10ml.png' WHERE name = 'Lemon Bottle';
UPDATE products SET image_url = '/product-images/68_LL-37_5mg.png' WHERE name = 'LL37';
UPDATE products SET image_url = '/product-images/11_AOD-9604_5mg.png' WHERE name = 'AOD-9604';
UPDATE products SET image_url = '/product-images/105_SLU-PP-322_5mg.png' WHERE name = 'SLU-PP-322';
UPDATE products SET image_url = '/product-images/SS-31_10mg.png' WHERE name = 'SS-31';
UPDATE products SET image_url = '/product-images/07_5-Amino-1MQ_10mg.png' WHERE name = '5-amino-1mq';
UPDATE products SET image_url = '/product-images/66_Lipo-C_10ml.png' WHERE name = 'Lipo-C';
UPDATE products SET image_url = '/product-images/67_Lipo-C_10ml_v2.png' WHERE name = 'Lipo-C with Vitamins B12 - Metabolic Boost';
UPDATE products SET image_url = '/product-images/L-Carnitine_10ml.png' WHERE name = 'L-Carnitine';
UPDATE products SET image_url = '/product-images/FATBLASTER_w_out_B12_10ml.png' WHERE name = 'FAT BLASTER LIPO-C *CLEAR (w/o Vitamin B12)';
UPDATE products SET image_url = '/product-images/39_FAT-BLASTER-LIPO-C-RED_10ml.png' WHERE name = 'FAT BLASTER LIPO-C *RED';
UPDATE products SET image_url = '/product-images/104_SHRED_10ml.png' WHERE name = 'SHRED';
UPDATE products SET image_url = '/product-images/LipoMinoMix_10ml.png' WHERE name = 'Lipo Mino Mix';
UPDATE products SET image_url = '/product-images/Heathy-Hair-skin.png' WHERE name = 'Healthy Hair Skin Nails Blend';
UPDATE products SET image_url = '/product-images/Super Human Blend_10ml.png' WHERE name = 'Super Human Blend';
UPDATE products SET image_url = '/product-images/82_Relaxation-PM_10ml.png' WHERE name = 'RELAXATION PM';
UPDATE products SET image_url = '/product-images/40_GABA-Relax-Blend_10ml.png' WHERE name = 'GABA Relax Blend';
UPDATE products SET image_url = '/product-images/15_Acetic-Acid_3ml.png' WHERE name = 'Acetic Acid Water';
UPDATE products SET image_url = '/product-images/17_Bacteriostatic-Water_3ml.png' WHERE name = 'Bacteriostatic Water';
UPDATE products SET image_url = '/product-images/BAC_Water_10ml.png' WHERE name = 'PharmaGrade Bac Water 10ml';
